eb-django-express-signup/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('form.urls')),
]

form/urls.py
from django.urls import path, re_path

from . import views

app_name = 'form'

urlpatterns = [
    # ex: /
    path('', views.home, name='home'),
    # ex: /signup
    path('signup', views.signup, name='signup'),
]

form/models.py
from django.db import models
import boto3
import os
import logging

STARTUP_SIGNUP_TABLE = os.environ['STARTUP_SIGNUP_TABLE']
AWS_REGION = os.environ['AWS_REGION']
AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
AWS_SESSION_TOKEN = os.environ['AWS_SESSION_TOKEN']


logger = logging.getLogger(__name__)


class Leads(models.Model):

    def insert_lead(self, name, email, previewAccess):
        try:
            dynamodb = boto3.resource('dynamodb',
                                      region_name=AWS_REGION,
                                      aws_access_key_id=AWS_ACCESS_KEY_ID,
                                      aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                                      aws_session_token=AWS_SESSION_TOKEN )
            table = dynamodb.Table(STARTUP_SIGNUP_TABLE)
        except Exception as e:
            logger.error(
                'Error connecting to database table: ' + (e.fmt if hasattr(e, 'fmt') else '') + ','.join(e.args))
            return 403
        try:
            response = table.put_item(
                Item={
                    'name': name,
                    'email': email,
                    'preview': previewAccess,
                },
                ReturnValues='ALL_OLD',
            )
        except Exception as e:
            logger.error(
                'Error adding item to database: ' + (e.fmt if hasattr(e, 'fmt') else '') + ','.join(e.args))
            return 403
        status = response['ResponseMetadata']['HTTPStatusCode']
        if status == 200:
            if 'Attributes' in response:
                logger.error('Existing item updated to database.')
                return 409
            logger.error('New item added to database.')
        else:
            logger.error('Unknown error inserting item to database.')

        return status

form/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Leads

def home(request):
    return render(request, 'form/index.html')


def signup(request):
    leads = Leads()
    status = leads.insert_lead(request.POST['name'], request.POST['email'], request.POST['previewAccess'])
    return HttpResponse('', status=status)

templates/form/index.html
{% extends "../generic.html" %}
{% block contents %}
    <div class="row justify-content-md-center">
        <div class="col-sm-8">
            <div id="signupSuccess" class="alert alert-success" style="display:none">
                <p id="signupSuccessText">Thanks for signing up!<br/>
                    You'll be among the first to know when we launch.</p>
            </div>
            <div id="signupDuplicate" class="alert alert-success" style="display:none">
                <p id="signupDuplicateText">Fear not, you're already on the list!<br/>
                    You'll be among the first to know when we launch.</p>
            </div>
            <div id="signupError" class="alert alert-info" style="display:none">
                <p id="signupErrorText">Well this is embarrassing.<br/>
                    It looks like we're having trouble getting you on the list.</p>
            </div>
            <div class="container-fluid  p-5" id="jumbohome">
                <h1>The next big thing is coming...</h1>
                <div class="row">
                    <div class="col-sm-9">
                        <p class="lead">We're pretty thrilled to unveil the subject you always wanted to enroll in.</p>
                        <p>Sign up below to be notified when we officially launch!</p>
                        <p>
                            <button type="button" class="btn btn-success" data-bs-toggle="modal"
                                    data-bs-target="#signupModal">Sign up today
                            </button>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal" tabindex="-1" id="signupModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Provide a few details and we'll be in touch...</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="signupForm" role="form">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="Your name">
                        </div>
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" class="form-control" id="email" name="email"
                                   placeholder="Your email address">
                        </div>
                        <div class="form-group">
                            <label for="previewAccess">Interested in Preview Access?</label>
                            <select class="form-control" name="previewAccess" id="previewAccess">
                                <option>Yes</option>
                                <option>No</option>
                            </select>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="signup">Submit</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {% csrf_token %}
    <script type="text/javascript">
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $(function () {
            $.ajaxSetup({
                beforeSend: function (xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
            $("#signup").click(function () {
                $.post("{% url 'form:signup' %}", $("#signupForm").serialize(),
                    function (data) {
                        $("#signupSuccess").show();
                    }
                ).error(function (xhr) {
                    switch (xhr.status) {
                        case 409:
                            $("#signupDuplicate").show();
                            break;
                        default:
                            $("#signupError").show();
                    }
                })
                    .always(function () {
                        $("#signupModal").modal('hide');
                    });
            })
        });
    </script>
{% endblock %}

templates/generic.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}"/>
    <title>Cloud Computing</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <div class="container">
        <a href="#" class="navbar-brand">Cloud Computing</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">
                <li class="nav-item active"><a class="nav-link active" href="{% url 'form:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#">About</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Blog</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Press</a></li>
            </ul>
        </div>
    </div>
</nav>
<main role="main">
    <div class="container-fluid  p-5" id="newstartup">
        <div class="container">
            <h1 class="display-3">Cloud Computing</h1>
        </div>
    </div>
    <div class="container">
        {% block contents %}<!-- /contents -->{% endblock %}
        <hr>
        <footer id="footer">
            <div class="row">
                <div class="col-lg-12">
                    <p>&copy; Cloud Computing 2023. <span class="pull-right">Made with <a target="_blank"
                                                                                          href="http://getbootstrap.com/">Bootstrap 5</a>.</span>
                    </p>
                </div>
            </div>
        </footer>
    </div>
</main>
<script src="https://code.jquery.com/jquery-2.2.4.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
{% block scripts %}<!-- /scripts -->{% endblock %}
</body>
</html>